name: CI workflow

on:
  push:
    branches: ["main", "dev"]

jobs:
  eslint:
    name: Run integration test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        continue-on-error: false

      - name: Run Test
        run: npm run test:ci
        continue-on-error: false
