name: Build and Deploy
on:
  push:
    branches: [master]

env:
  GITHUB_TOKEN: ${{ env.TOKEN_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}

      - name: Install 🔧
        run: npm install

      - name: Build 🔧
        run: |
          npm run export
          touch out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          BRANCH: production # Nama branch yang akan digunakan.
          FOLDER: out # Folder yang akan dideploy
          CLEAN: true # Hapus file di dalam branch
